title: Rizvi Hasan
description: Sr. Data Scientist with Engineering Experience
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
email1: rizvi.kth@gmail.com
github:
    zip_url: https://rizviof0.wordpress.com/author/rizvidu/
    tar_url: ../coming_soon.html
